# Generated by Django 2.0.7 on 2018-07-16 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=255, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('language', models.CharField(blank=True, max_length=255, null=True)),
                ('copyright', models.CharField(blank=True, max_length=255, null=True)),
                ('managing_editor', models.CharField(blank=True, max_length=255, null=True)),
                ('web_master', models.CharField(blank=True, max_length=255, null=True)),
                ('generator', models.CharField(blank=True, max_length=255, null=True)),
                ('docs', models.CharField(blank=True, max_length=255, null=True)),
                ('rating', models.CharField(blank=True, max_length=255, null=True)),
                ('pub_date', models.CharField(blank=True, max_length=255, null=True)),
                ('last_build_date', models.CharField(blank=True, max_length=255, null=True)),
                ('ttl', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('link', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('width', models.PositiveSmallIntegerField(default=88)),
                ('height', models.PositiveSmallIntegerField(default=31)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='example_app.Channel')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('link', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('author', models.CharField(blank=True, max_length=255, null=True)),
                ('comments', models.CharField(blank=True, max_length=255, null=True)),
                ('guid', models.CharField(blank=True, max_length=255, null=True)),
                ('pubDate', models.CharField(blank=True, max_length=255, null=True)),
                ('source', models.CharField(blank=True, max_length=255, null=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='example_app.Channel')),
            ],
        ),
    ]
